name: inicie_todo_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  go_router: ^16.2.4
  intl: ^0.20.2
  mask_text_input_formatter: ^2.9.0
  riverpod: ^3.0.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0
  mockito: ^5.5.0
  build_runner: ^2.7.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/montserrat/
    - assets/fonts/roboto/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
