// Mocks generated by Mockito 5.4.6 from annotations
// in inicie_todo_test/test/mocks/mocks.mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:inicie_todo_test/src/core/failures/failures.dart' as _i8;
import 'package:inicie_todo_test/src/core/storage/wrapper/shared_preferences_wrapper.dart'
    as _i3;
import 'package:inicie_todo_test/src/features/tasks/data/datasource/task_local_data_source.dart'
    as _i5;
import 'package:inicie_todo_test/src/features/tasks/data/models/task_model.dart'
    as _i6;
import 'package:inicie_todo_test/src/features/tasks/domain/entities/task_entity.dart'
    as _i9;
import 'package:inicie_todo_test/src/features/tasks/domain/repositories/task_repository.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [KeyValueWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyValueWrapper extends _i1.Mock implements _i3.KeyValueWrapper {
  MockKeyValueWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  _i4.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [TasksLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTasksLocalDataSource extends _i1.Mock
    implements _i5.TasksLocalDataSource {
  MockTasksLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i6.TaskModel>> getAllTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTasks, []),
            returnValue: _i4.Future<List<_i6.TaskModel>>.value(
              <_i6.TaskModel>[],
            ),
          )
          as _i4.Future<List<_i6.TaskModel>>);

  @override
  _i4.Future<void> saveAllTasks(List<_i6.TaskModel>? tasks) =>
      (super.noSuchMethod(
            Invocation.method(#saveAllTasks, [tasks]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i6.TaskModel?> getTaskById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskById, [id]),
            returnValue: _i4.Future<_i6.TaskModel?>.value(),
          )
          as _i4.Future<_i6.TaskModel?>);
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i7.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i8.Failure, List<_i9.TaskEntity>>> getAllTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTasks, []),
            returnValue:
                _i4.Future<_i2.Either<_i8.Failure, List<_i9.TaskEntity>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.TaskEntity>>(
                    this,
                    Invocation.method(#getAllTasks, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i8.Failure, List<_i9.TaskEntity>>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, _i9.TaskEntity>> getTaskById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskById, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i8.Failure, _i9.TaskEntity>>.value(
                  _FakeEither_0<_i8.Failure, _i9.TaskEntity>(
                    this,
                    Invocation.method(#getTaskById, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i8.Failure, _i9.TaskEntity>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> deleteFromId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFromId, [id]),
            returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
              _FakeEither_0<_i8.Failure, void>(
                this,
                Invocation.method(#deleteFromId, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> deleteFromIdRange(
    Iterable<String>? ids,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFromIdRange, [ids]),
            returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
              _FakeEither_0<_i8.Failure, void>(
                this,
                Invocation.method(#deleteFromIdRange, [ids]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> updateFromId(
    String? id,
    _i9.TaskEntity? task,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateFromId, [id, task]),
            returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
              _FakeEither_0<_i8.Failure, void>(
                this,
                Invocation.method(#updateFromId, [id, task]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> createTask(_i9.TaskEntity? task) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [task]),
            returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
              _FakeEither_0<_i8.Failure, void>(
                this,
                Invocation.method(#createTask, [task]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i8.Failure, void>>);
}
